# TODO: maybe one day improve JSON-LD metadata (it's pretty complicated)
# https://code.luasoftware.com/tutorials/hugo/schema-markup-for-hugo/

title = "Richard Si"
languageCode = 'en-ca'
defaultContentLanguage = "en-ca"
timeZone = "America/Toronto"
copyright = "© 2022-present, Richard Si"

theme = "PaperMod"

baseURL = 'https://ichard26.github.io/'
enableGitInfo = true
enableRobotsTXT = true
paginate = 8

[frontmatter]
date = ["date", ":filename"]
publishDate = ["publishDate", "date", ":filename"]
lastmod = ["lastmod"]

[permalinks]
blog = "blog/:year/:month/:slug/"

[params]
description = "A place for Richard Si (@ichard26) to ramble about Python and open-source software."
defaultTheme = "auto"
showReadingTime = true
showCodeCopyButtons = true
showPostNavLinks = true
ShowRssButtonInSectionTermList = true
# ShowShareButtons = true
env = "development"
keywords = ["blog", "python", "black", "oss", "foss"]

# Shown on the home page
socialIcons = [
  { name = "email", url = "mailto:sichard26@gmail.com" },
  { name = "github", url = "https://github.com/ichard26" },
  # { name = "twitter", url = "https://twitter.com/sichard26" },
  { name = "python discourse", url = "https://discuss.python.org/u/ichard26/summary" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/18155471/ichard26"},
  # { name = "reddit", url = "https://www.reddit.com/user/ichard26" },
]

[params.schema]
publisherType = "Person"
sameAs = [
  "https://github.com/ichard26",
  "https://twitter.com/sichard26",
  "https://discuss.python.org/u/ichard26/summary",
  "https://stackoverflow.com/users/18155471/ichard26",
  "https://www.reddit.com/user/ichard26",
  "https://pypi.org/user/ichard26/",
  "https://readthedocs.org/profiles/ichard26/",
]

[taxonomies]
  tag = 'tags'

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Richard."
subtitle = "I'm a hobby Python developer & FOSS maintainer who likes flowers."
imageUrl = "/flower-profile-picture.webp"
buttons = [
  { name = "Next PR Number", url = "https://ichard26.github.io/next-pr-number/" }
]

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "About"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "writing"
name = "writing"
title = "Writing"
url = "/blog/"

[[menu.main]]
weight = 3
identifier = "privacy"
name = "privacy"
title = "Privacy Statement"
url = "/privacy/"

# Allow HTML in my content pages.
[markup.goldmark.renderer]
unsafe = true
