title = "Richard Si"
languageCode = 'en-ca'
defaultContentLanguage = "en-ca"
timeZone = "Canada/Eastern"
copyright = "© 2022-present, Richard Si"

theme = "PaperMod"

baseURL = 'https://ichard26.github.io/'
enableRobotsTXT = true
paginate = 15

[frontmatter]
date = ["date", ":filename"]
publishDate = ["publishDate", "date", ":filename"]
lastmod = ["lastmod", ":fileModTime", "date", ":filename"]

[permalinks]
blog = "blog/:year/:month/:day/:slug/"

[params]
description = "Richard Si (ichard26)'s personal place for F/OSS writings."
defaultTheme = "auto"
showReadingTime = true
showCodeCopyButtons = true
showPostNavLinks = true
env = "development"
keywords = ["blog", "python", "oss", "foss"]

# Shown on the home page
socialIcons = [
  { name = "github", url = "https://github.com/ichard26" },
  { name = "python", url = "https://discuss.python.org/u/ichard26/summary" },
  { name = "reddit", url = "https://www.reddit.com/user/ichard26" },
]

[taxonomies]
  tag = 'tags'

# Configure the home page
[params.profileMode]
enabled = true
title = "Hi, I'm Richard ❀"
subtitle = "I'm a Python F/OSS maintainer who likes flowers."
imageUrl = "/flower-profile-picture.webp"

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "About"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "writing"
name = "writing"
title = "Writing"
url = "/blog/"

[[menu.main]]
weight = 3
identifier = "privacy"
name = "privacy"
title = "Privacy Statement"
url = "/privacy/"

# Allow HTML in my content pages.
[markup.goldmark.renderer]
unsafe = true
